export default {
  code: 'en',

  t: {
    skip: 'Skip to content',
    heroTagline: 'Deafblind Activist',
    aboutTitle: 'About',
    aboutSubtitle: 'Who I am and what I work on.',
    moreAbout: 'More about me →',
    uberMichText:
      'As a deafblind person, I have worked for over ten years on digital and social participation. I give talks, serve on the board of a professional association, and work as a lecturer – drawing on lived experience and a clear commitment to accessibility for everyone.',
    aboutP1:
      "I'm Til Apfel, deafblind since childhood. This dual sensory impairment has sharpened my view of accessibility – not as a checklist, but as a basic requirement for a self-determined life.",
    aboutP2:
      'As an activist and lecturer, I talk at conferences, congresses and schools about deafblindness, assistive technology and digital participation. As a board member of a professional association, I represent the interests of deafblind people to policymakers and institutions.',
    aboutP3:
      'My motivation is simple: no one should be excluded from information, education or participation because of missing accessibility – and I work on changing that every day.',
    haltungHeading: 'My Approach',
    rollenHeading: 'Roles',
    werteHeading: 'Values',
    aboutCtaText: 'Interested in working together?',
    aboutCtaLink: 'Get in touch',
    portfolioTitle: 'Projects',
    portfolioSubtitle: 'Projects and milestones I am working on.',
    focusTitle: 'Feeds',
    focusSubtitle: 'What I stand for – and where you can follow along.',
    focusClosing: "I'm generally approachable and bookable on these topics.",
    moreFocus: 'More on my focus →',
    feedsChannelsHeading: 'My Channels',
    feedsPostsHeading: 'Latest Posts',
    feedsTopicsHeading: 'My Topics',
    feedsTagAll: 'All',
    eventsTitle: 'Events',
    eventsSubtitle: 'Where you can meet and book me.',
    registerBtn: 'Register for this event',
    upcomingHeading: 'Upcoming Events',
    bookableHeading: 'Bookable Formats',
    ctaKostenvoranschlag: 'Request a quote',
    pastHeading: 'Past Events',
    libraryTitle: 'Library',
    librarySubtitle: 'What I have published.',
    publicationsHeading: 'Publications',
    pressHeading: 'Press & Media',
    moreLibrary: 'Go to Library →',
    impressumSubtitle: 'Legal information about me.',
    impressumPlaceholder: 'Placeholder',
    impressumPhoneLabel: 'Phone',
    impressumEmailLabel: 'Email',
    impressumDatenschutzLink: 'See also: Privacy Policy →',
    formularTitle: 'Request a Quote',
    formularSubtitle: 'Ask me for a quote.',
    kontaktTitle: 'Contact',
    kontaktSubtitle: 'Send me a message.',
    datenschutzTitle: 'Privacy Policy',
    datenschutzSubtitle: 'How I handle your data.',
    errorTitle: 'Not accessible',
    errorBody:
      "For once, that's not a bug: this page simply doesn't exist. The rest of the site does — and it's fully accessible.",
    errorHomeLink: 'Back to home',
    consentPrefix: 'I have read the',
    consentLinkText: 'Privacy Policy',
    consentSuffix: 'and agree to it.',
    formErrorRateLimited: 'Too many requests. Please try again later.',
    formErrorGeneric: 'Something went wrong while sending. Please try again.',
    language: 'Language',
    darkReaderNotice:
      "This site already has a built-in dark mode – the Dark Reader extension isn't needed here and may distort the display.",
    newsletterHeading: 'Newsletter',
    newsletterDesc: 'Updates on talks, projects and accessibility topics – every once in a while, no spam.',
    newsletterFirstNameLabel: 'First name',
    newsletterEmailLabel: 'Email address',
    newsletterPlaceholder: 'you@email.com',
    newsletterSubmitBtn: 'Subscribe',
    newsletterEmailSubject: 'Newsletter signup',
    newsletterBioLabel: 'Subscribe to newsletter',
    newsletterBioDesc: 'Stay up to date',
    labelNachricht: 'Message',
    kontaktSubmitBtn: 'Send message',
    labelName: 'Name',
    labelEmail: 'Email',
    labelArt: 'Type of request',
    labelBeschreibung: 'Description',
    labelZeitrahmen: 'Desired timeframe',
    submitBtn: 'Send request',
    alleProjekte: 'View all Projects →',
    alleTermine: 'View all events →',
    footerImpressum: 'Legal Notice',
    closeDialog: 'Close',
    bioIntro:
      'Deafblind activist and advocate. I work for the digital and social participation of deafblind people.',
    emailSubjectRegistration: 'Registration: ',
    emailSubjectContact: 'Contact form message',
    emailSubjectQuote: 'Quote request: ',
    navAriaLabel: 'Main navigation',
    portraitAlt: 'Portrait of Til Apfel',
    themeToLight: 'Switch to light mode',
    themeToDark: 'Switch to dark mode',
    moreEventsTemplate: 'Show {n} more events',
    aboutBioLink: 'All links at a glance →',
    share: 'Share',
    copyLink: 'Copy link',
    linkCopied: 'Link copied!',
    search: 'Search',
    searchPlaceholder: 'Search the site…',
    searchNoResults: 'No results',
    searchLabel: 'Search term',
    searchResultsCountSingular: '{count} result found',
    searchResultsCountPlural: '{count} results found',
    easyLanguage: 'Easy language',
    easyLanguageOn: 'On',
    easyLanguageOff: 'Off',
    easyLanguageUnavailableForDgs: 'Easy language is not available for DGS.',
    dgsNoticeTitle: 'Content in German Sign Language',
    dgsNoticeBody:
      'A German Sign Language (DGS) video for this content is coming soon. Until then, the text below is available in German.',
    onboardingTitle: 'Welcome',
    onboardingIntro: 'Before you start: how would you like to use the site?',
    onboardingLangLabel: 'Language',
    onboardingThemeLabel: 'Brightness',
    onboardingLight: 'Light',
    onboardingDark: 'Dark',
    onboardingDone: 'Get started',
  },

  nav: { about: 'About', projects: 'Projects', feeds: 'Feeds', events: 'Events', library: 'Library' },

  bioPrimary: [
    { label: 'All info about Til Apfel' },
    { label: 'Til Apfel Foundation' },
    { label: 'Apps developed by Til Apfel' },
  ],

  impressumAddress: {
    name: 'Til Apfel',
    street: 'Musterstraße 12',
    city: '12345 Musterstadt',
    phone: '+49 (0) 123 456789',
  },

  impressumSections: [
    {
      heading: 'Responsible for content under German law (§ 55 (2) RStV)',
      body: 'Til Apfel, address as above.',
    },
    {
      heading: 'EU Dispute Resolution',
      body: 'The European Commission provides a platform for online dispute resolution (ODR): https://ec.europa.eu/consumers/odr/. I am not obliged or willing to participate in dispute resolution proceedings before a consumer arbitration board.',
    },
    {
      heading: 'Liability for Content',
      body: 'As a service provider, I am responsible for my own content on these pages under general law (§ 7 (1) TMG). Under §§ 8 to 10 TMG, however, I am not obliged as a service provider to monitor transmitted or stored third-party information or to investigate circumstances that indicate unlawful activity.',
    },
    {
      heading: 'Liability for Links',
      body: 'This website contains links to external third-party websites over whose content I have no influence. I therefore cannot accept any liability for this external content. The respective provider or operator of a linked page is always responsible for its content.',
    },
    {
      heading: 'Copyright',
      body: 'The content and works created by me on these pages are subject to German copyright law. Reproduction, editing, distribution and any kind of exploitation beyond the limits of copyright require written consent.',
    },
  ],

  datenschutzSections: [
    {
      heading: 'Controller',
      body: 'The controller responsible for data processing on this website is Til Apfel (contact details see Legal Notice).',
    },
    {
      heading: 'Hosting',
      body: 'This website is hosted with an external hosting provider. When you visit the site, technical access data (e.g. IP address, date and time, page requested) is automatically recorded in server log files. This data serves the technical provision and security of the website (Art. 6(1)(f) GDPR).',
    },
    {
      heading: 'Contact forms',
      body: 'The forms on this website (Contact, Quote request) do not submit your entries to a server; instead they open your local email client with a pre-filled message. The actual transmission only happens once you send that email yourself – no entries are stored on this website.',
    },
    {
      heading: 'Spam protection',
      body: "Before a form can be submitted, a function on our server automatically checks whether the request looks like it came from a bot rather than a person (e.g. based on how quickly the form was filled in and how many requests recently came from the same IP address). Your IP address is briefly processed for this purpose but not stored permanently. We deliberately don't use a CAPTCHA, so the form stays accessible to everyone. The legal basis is our legitimate interest in protecting our forms from spam and abuse (Art. 6(1)(f) GDPR).",
    },
    {
      heading: 'Google Fonts',
      body: 'This website uses the "Inter" typeface from Google Fonts, which is loaded from Google\'s servers when the page is visited. This transmits your IP address to Google. The legal basis is our legitimate interest in a consistent presentation of the website (Art. 6(1)(f) GDPR).',
    },
    {
      heading: 'Local storage in your browser',
      body: 'Your preferences for language, brightness and easy language are stored exclusively in your browser (localStorage) and are not transmitted to us or third parties.',
    },
    {
      heading: 'Your rights',
      body: 'You have the right to access, rectify, erase and restrict the processing of your personal data, as well as the right to object to processing. You also have the right to lodge a complaint with the competent data protection supervisory authority.',
    },
  ],

  roles: [
    {
      key: 'activist',
      label: 'Activism',
      desc: 'Advocacy for the rights and visibility of deafblind people.',
    },
    {
      key: 'board',
      label: 'Board',
      desc: 'Advocacy in the professional association for deafblind people.',
    },
    {
      key: 'lecturer',
      label: 'Lecturing',
      desc: 'Teaching accessibility and participation through talks and courses.',
    },
    {
      key: 'consulting',
      label: 'Consulting',
      desc: 'Consulting on accessible software design for public bodies, associations and companies.',
    },
    {
      key: 'projectManagement',
      label: 'Project Management',
      desc: 'Steering accessibility projects from concept through implementation.',
    },
  ],

  auftragArten: ['Consulting', 'Talk', 'Software Development', 'Other'],

  portfolio: [
    {
      tagSlug: 'education',
      dateSlug: '2010',
      date: 'Since 2010',
      category: 'Education',
      location: 'Placeholder',
      title: 'Studies & Training',
      short: 'Foundational education underlying the current work.',
      full: 'Details on degree program and training stages will be added here soon.',
      approach: '(Placeholder – to be added)',
    },
    {
      tagSlug: 'career',
      dateSlug: '2019',
      date: 'Since 2019',
      category: 'Career Path',
      location: 'Self-employed',
      title: 'Building a Career as a Lecturer',
      short: 'Developing independent speaking and teaching work.',
      full: 'For several years I have been building independent work as a lecturer and speaker – from first individual talks to regular teaching assignments.',
      approach:
        'The path led from volunteer talks to paid assignments with educational institutions, associations and companies.',
    },
    {
      tagSlug: 'ngo',
      dateSlug: '2021',
      date: 'Since 2021',
      category: 'NGO Engagement',
      location: 'Deafblind Association',
      title: 'Board Work at the Deafblind Association',
      short: 'Representing deafblind people at the association level.',
      full: 'As a board member, I represent the interests of deafblind people to policymakers, funding bodies and the public.',
      approach:
        'This includes position papers, talks with ministries and following legislation on participation.',
    },
    {
      tagSlug: 'ngo',
      dateSlug: '2022',
      date: 'Since 2022',
      category: 'NGO Engagement',
      location: 'European Deafblind Union',
      title: 'Work with the European Deafblind Union',
      short: 'Engagement for shared European standards.',
      full: 'Contributing to a European working group on standards and recommendations for assistive technology for deafblind people.',
      approach:
        'The working group brings together representatives from several European countries to develop shared minimum standards.',
    },
    {
      tagSlug: 'project',
      dateSlug: '2023',
      date: 'Since 2023',
      category: 'Own Project',
      location: 'Nationwide',
      title: 'Accessible Digitalization',
      short: 'Ongoing consulting project for public bodies and companies.',
      full: 'Consulting for public bodies and companies implementing accessible software and websites – from initial concept to screen reader testing.',
      approach:
        'I work closely with development teams and audit existing applications using my own screen reader and braille display practice.',
    },
    {
      tagSlug: 'journey',
      dateSlug: '2015',
      date: '2015–2018',
      category: 'Personal Path',
      location: 'Self-taught',
      title: 'Programming as a Deafblind Person',
      short: 'Learning software development despite a lack of accessible learning paths.',
      full: 'I largely taught myself programming – using a screen reader and braille display, often without accessible learning materials.',
      approach: 'This path still shapes how I design software for other deafblind users today.',
    },
  ],

  termine: [
    {
      tagSlug: 'talk',
      dateSlug: '2026-07-22',
      date: 'July 22, 2026',
      category: 'Talk',
      title: 'Digital Participation Today',
      location: 'Inclusion Conference, Berlin',
      detail:
        'A talk on the current state of digital participation in Germany, focused on public administration and education.',
      info: 'Audience: professionals from administration and education. Duration: 45 minutes incl. Q&A.',
    },
    {
      tagSlug: 'board',
      dateSlug: '2026-08-05',
      date: 'August 5, 2026',
      category: 'Board',
      title: 'Deafblind Association Board Meeting',
      location: 'Association Office, Cologne',
      detail: 'Regular board meeting covering ongoing applications, budget and upcoming association events.',
      info: 'Internal to the association – attendance by arrangement with the office.',
    },
    {
      tagSlug: 'workshop',
      dateSlug: '2026-09-14',
      date: 'September 14, 2026',
      category: 'Workshop',
      title: 'Designing Accessible Software',
      location: 'Online',
      detail:
        'Hands-on workshop for engineering teams: testing your own applications together with a screen reader and braille display.',
      info: 'Audience: developers and product teams. Duration: 3 hours, max. 15 participants.',
    },
    {
      tagSlug: 'talk',
      dateSlug: '2026-10-02',
      date: 'October 2, 2026',
      category: 'Talk',
      title: 'Living Deafblind – A First-Hand Account',
      location: 'University of Vienna',
      detail:
        'A personal account of everyday life, communication and self-determination as a deafblind person.',
      info: 'Audience: students and the public. Duration: 60 minutes.',
    },
    {
      tagSlug: 'international',
      dateSlug: '2026-10-20',
      date: 'October 20, 2026',
      category: 'International',
      title: 'EDBU Working Group Meeting',
      location: 'Brussels',
      detail: 'Two-day meeting of the European technology working group to align on shared standards.',
      info: 'By invitation of the European Deafblind Union.',
    },
    {
      tagSlug: 'workshop',
      dateSlug: '2026-11-11',
      date: 'November 11, 2026',
      category: 'Workshop',
      title: 'Screen Reader Testing for Dev Teams',
      location: 'Hamburg',
      detail:
        'Hands-on workshop on systematically testing web and app interfaces with common screen readers.',
      info: 'Audience: QA and engineering. Duration: full day.',
    },
  ],

  pastTermine: [
    {
      date: 'May 8, 2025',
      category: 'International',
      title: 'EDBU General Assembly',
      location: 'Copenhagen',
    },
    {
      date: 'November 12, 2025',
      category: 'Talk',
      title: 'Inclusion Days Frankfurt',
      location: 'Frankfurt am Main',
    },
  ],

  library: [
    {
      slug: 'accessnav',
      type: 'App',
      title: 'AccessNav',
      desc: 'Navigation app with tactile and audio feedback for deafblind users.',
    },
    {
      slug: 'dual-sensory-impairment',
      type: 'Essay',
      title: 'Dual Sensory Impairment',
      desc: 'An article on the specific accessibility requirements involved.',
    },
    {
      slug: 'zwischentoene',
      type: 'Podcast',
      title: 'Zwischentöne',
      desc: 'An interview series with activists from the disability rights movement.',
    },
  ],

  press: [
    {
      outlet: 'Deutschlandfunk',
      date: 'April 2025',
      title: 'When Two Senses Are Missing, the Voice Grows Louder',
    },
    { outlet: 'Süddeutsche Zeitung', date: 'November 2024', title: 'The Man Who Codes Away Barriers' },
    { outlet: 'taz', date: 'February 2026', title: 'Participation Is Not a Question of Technology Alone' },
  ],

  focusItems: [
    { title: 'Association Work at TBV and EDBU', desc: 'Advocacy at the national and European level.' },
    {
      title: 'Building a Career as a Lecturer',
      desc: 'Independent speaking and teaching work around accessibility.',
    },
    {
      title: 'Learning to Program as Deafblind',
      desc: 'Access to software development despite a lack of accessible learning paths.',
    },
  ],

  feedsPosts: [
    {
      formatSlug: 'youtube',
      dateSlug: '2026-06',
      date: 'June 2026',
      source: 'YouTube',
      tags: ['Talk'],
      title: 'Clip: Digital Participation Today',
      desc: 'Short video clip from a recent talk on digital participation. (Placeholder – real link to follow)',
    },
    {
      formatSlug: 'blog',
      dateSlug: '2026-05',
      date: 'May 2026',
      source: 'Blog',
      tags: ['Accessibility'],
      title: "Why Accessibility Isn't an Extra",
      desc: 'A blog post on why accessibility needs to be designed in from the start. (Placeholder – real link to follow)',
    },
    {
      formatSlug: 'podcast',
      dateSlug: '2026-04',
      date: 'April 2026',
      source: 'Podcast',
      tags: ['Interview'],
      title: 'Guest on Zwischentöne',
      desc: 'Interview on deafblindness and digital participation on the Zwischentöne podcast. (Placeholder – real link to follow)',
    },
    {
      formatSlug: 'linkedin',
      dateSlug: '2026-03',
      date: 'March 2026',
      source: 'LinkedIn',
      tags: ['Association'],
      title: 'Recap: EDBU Working Group Meeting',
      desc: 'A short recap of the latest European Deafblind Union working group meeting. (Placeholder – real link to follow)',
    },
    {
      formatSlug: 'blog',
      dateSlug: '2026-02',
      date: 'February 2026',
      source: 'Blog',
      tags: ['Programming'],
      title: 'Programming with a Screen Reader – A Workshop Report',
      desc: 'A look into my everyday work as a developer using a screen reader and braille display. (Placeholder – real link to follow)',
    },
  ],

  werte: [
    'Software Development (Programming)',
    'Plant-Based Cooking (Vegan)',
    'Mental Health (Psychology)',
    'Outdoor Activities (Nature Sports)',
    'Human Rights (Justice)',
  ],

  principles: [
    'Accessibility is not an extra, it is the foundation.',
    'Participation comes from access, not from pity.',
    'I show what is possible with the right tools.',
  ],

  bookable: [
    {
      slug: 'vortrag',
      title: 'Talk',
      desc: 'Talks on deafblindness, accessibility and digital participation for professionals and schools.',
      full: 'Talks are aimed at professional audiences, educational institutions and conferences. Topics range from deafblindness and assistive technology to everyday digital participation. Talks are available in person or online, with duration and content tailored individually.',
    },
    {
      slug: 'beratung',
      title: 'Consulting',
      desc: 'Accessibility audits and consulting for public bodies, associations and companies.',
      full: 'Consulting includes accessibility audits of existing websites and applications, implementation recommendations, and support with practical testing using a screen reader and braille display. Suited for public bodies, associations and companies looking to make their digital offerings accessible.',
    },
    {
      slug: 'dozent',
      title: 'Lecturing',
      desc: 'Courses and workshops on accessible software design.',
      full: 'Courses and workshops provide hands-on guidance on how accessible software is built – from concept through implementation to testing. Format and scope are tailored to the requirements of the educational institution or development team.',
    },
  ],
};
